from decouple import config

class Config:
    pass

class DevelopmentConfig(Config):
    DEBUG = True
    CANILLITA_TWITTER_CONSUMER_KEY = config('TWITTER_CONSUMER_KEY')
    CANILLITA_TWITTER_CONSUMER_SECRET = config('TWITTER_CONSUMER_SECRET')
    CANILLITA_TWITTER_ACCESS_TOKEN = config('TWITTER_ACCESS_TOKEN')
    CANILLITA_TWITTER_ACCESS_TOKEN_SECRET = config('TWITTER_ACCESS_TOKEN_SECRET')

class ProductionConfig(Config):
    DEBUG = False
    SQLALCHEMY_DATABASE_URI = config('DATABASE_URL', default='localhost')
    CANILLITA_TWITTER_CONSUMER_KEY = config('TWITTER_CONSUMER_KEY')
    CANILLITA_TWITTER_CONSUMER_SECRET = config('TWITTER_CONSUMER_SECRET')
    CANILLITA_TWITTER_ACCESS_TOKEN = config('TWITTER_ACCESS_TOKEN')
    CANILLITA_TWITTER_ACCESS_TOKEN_SECRET = config('TWITTER_ACCESS_TOKEN_SECRET')


config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig
}